export type Style = {
  tokenColors: {
    [K in TokenType]: TokenColor;
  };
};

export enum TokenType {
  Variable = "variable",
  VariableBuiltin = "variable.builtin",
  VariableParameter = "variable.parameter",
  VariableParameterBuiltin = "variable.parameter.builtin",
  VariableMember = "variable.member",
  Constant = "constant",
  ConstantBuiltin = "constant.builtin",
  ConstantMacro = "constant.macro",
  Module = "module",
  ModuleBuiltin = "module.builtin",
  Label = "label",
  String = "string",
  StringDocumentation = "string.documentation",
  StringEscape = "string.escape",
  StringRegexp = "string.regexp",
  StringSpecial = "string.special",
  StringSpecialUrl = "string.special.url",
  StringSpecialPath = "string.special.path",
  StringSpecialSymbol = "string.special.symbol",
  Character = "character",
  CharacterSpecial = "character.special",
  Boolean = "boolean",
  Number = "number",
  NumberFloat = "number.float",
  Type = "type",
  TypeBuiltin = "type.builtin",
  TypeDefinition = "type.definition",
  Attribute = "attribute",
  AttributeBuiltin = "attribute.builtin",
  Property = "property",
  Function = "function",
  FunctionBuiltin = "function.builtin",
  FunctionMacro = "function.macro",
  FunctionCall = "function.call",
  FunctionMethod = "function.method",
  FunctionMethodCall = "function.method.call",
  Constructor = "constructor",
  Operator = "operator",
  Keyword = "keyword",
  KeywordCoroutine = "keyword.coroutine",
  KeywordFunction = "keyword.function",
  KeywordOperator = "keyword.operator",
  KeywordImport = "keyword.import",
  KeywordType = "keyword.type",
  KeywordModifier = "keyword.modifier",
  KeywordRepeat = "keyword.repeat",
  KeywordReturn = "keyword.return",
  KeywordDebug = "keyword.debug",
  KeywordException = "keyword.exception",
  KeywordConditional = "keyword.conditional",
  KeywordConditionalTernary = "keyword.conditional.ternary",
  KeywordDirective = "keyword.directive",
  KeywordDirectiveDefine = "keyword.directive.define",
  PunctuationDelimiter = "punctuation.delimiter",
  PunctuationBracket = "punctuation.bracket",
  PunctuationSpecial = "punctuation.special",
  Comment = "comment",
  CommentDocumentation = "comment.documentation",
  CommentError = "comment.error",
  CommentTodo = "comment.todo",
  CommentWarning = "comment.warning",
  CommentNote = "comment.note",
  MarkupStrong = "markup.strong",
  MarkupItalic = "markup.italic",
  MarkupUnderline = "markup.underline",
  MarkupStrikethrough = "markup.strikethrough",
  MarkupLink = "markup.link",
  MarkupLinkLabel = "markup.link.label",
  MarkupLinkUrl = "markup.link.url",
  MarkupHeading = "markup.heading",
  MarkupHeading1 = "markup.heading.1",
  MarkupHeading2 = "markup.heading.2",
  MarkupHeading3 = "markup.heading.3",
  MarkupHeading4 = "markup.heading.4",
  MarkupHeading5 = "markup.heading.5",
  MarkupHeading6 = "markup.heading.6",
  MarkupList = "markup.list",
  MarkupListUnchecked = "markup.list.unchecked",
  MarkupListChecked = "markup.list.checked",
  MarkupQuote = "markup.quote",
  MarkupMath = "markup.math",
  MarkupRaw = "markup.raw",
  MarkupRawBlock = "markup.raw.block",
  DiffPlus = "diff.plus",
  DiffMinus = "diff.minus",
  DiffDelta = "diff.delta",
  Tag = "tag",
  TagDelimiter = "tag.delimiter",
  TagAttribute = "tag.attribute",
  TagBuiltin = "tag.builtin",
  None = "none",
  Conceal = "conceal",
  Spell = "spell",
  Nospell = "nospell",
}

export type TokenColor = `#${string}`;

export let test_style: Style = {
  tokenColors: {
    [TokenType.Variable]: "#bfbdb6",
    [TokenType.VariableBuiltin]: "#39bae6",
    [TokenType.VariableParameter]: "#bfbdb6",
    [TokenType.VariableParameterBuiltin]: "#ff0000",
    [TokenType.VariableMember]: "#f07178",
    [TokenType.Constant]: "#ff0000",
    [TokenType.ConstantBuiltin]: "#d2a6ff",
    [TokenType.ConstantMacro]: "#ff0000",
    [TokenType.Module]: "#ff0000",
    [TokenType.ModuleBuiltin]: "#ff0000",
    [TokenType.Label]: "#ff0000",
    [TokenType.String]: "#aad94c",
    [TokenType.StringDocumentation]: "#ff0000",
    [TokenType.StringEscape]: "#ff0000",
    [TokenType.StringRegexp]: "#95e6cb",
    [TokenType.StringSpecial]: "#ff0000",
    [TokenType.StringSpecialUrl]: "#ff0000",
    [TokenType.StringSpecialPath]: "#ff0000",
    [TokenType.StringSpecialSymbol]: "#ff0000",
    [TokenType.Character]: "#ff0000",
    [TokenType.CharacterSpecial]: "#ff0000",
    [TokenType.Boolean]: "#ff0000",
    [TokenType.Number]: "#d2a6ff",
    [TokenType.NumberFloat]: "#d2a6ff",
    [TokenType.Type]: "#ff0000",
    [TokenType.TypeBuiltin]: "#ff0000",
    [TokenType.TypeDefinition]: "#ff0000",
    [TokenType.Attribute]: "#ff0000",
    [TokenType.AttributeBuiltin]: "#ff0000",
    [TokenType.Property]: "#ff0000",
    [TokenType.Function]: "#ffb454",
    [TokenType.FunctionBuiltin]: "#ffb454",
    [TokenType.FunctionMacro]: "#ff0000",
    [TokenType.FunctionCall]: "#ff0000",
    [TokenType.FunctionMethod]: "#ff0000",
    [TokenType.FunctionMethodCall]: "#ff0000",
    [TokenType.Constructor]: "#ff0000",
    [TokenType.Operator]: "#ff0000",
    [TokenType.Keyword]: "#ff8f40",
    [TokenType.KeywordCoroutine]: "#ff8f40",
    [TokenType.KeywordFunction]: "#ff8f40",
    [TokenType.KeywordOperator]: "#f29668",
    [TokenType.KeywordImport]: "#ff8f40",
    [TokenType.KeywordType]: "#ff8f40",
    [TokenType.KeywordModifier]: "#ff8f40",
    [TokenType.KeywordRepeat]: "#ff8f40",
    [TokenType.KeywordReturn]: "#ff8f40",
    [TokenType.KeywordDebug]: "#ff8f40",
    [TokenType.KeywordException]: "#ff0000",
    [TokenType.KeywordConditional]: "#ff8f40",
    [TokenType.KeywordConditionalTernary]: "#ff8f40",
    [TokenType.KeywordDirective]: "#ff8f40",
    [TokenType.KeywordDirectiveDefine]: "#ff8f40",
    [TokenType.PunctuationDelimiter]: "#bfbdb6b3",
    [TokenType.PunctuationBracket]: "#ff0000",
    [TokenType.PunctuationSpecial]: "#ff8f40",
    [TokenType.Comment]: "#acb6bf8c",
    [TokenType.CommentDocumentation]: "#acb6bf8c",
    [TokenType.CommentError]: "#FF2D00",
    [TokenType.CommentTodo]: "#FF8C00",
    [TokenType.CommentWarning]: "#ffbb00",
    [TokenType.CommentNote]: "#98C379",
    [TokenType.MarkupStrong]: "#ff0000",
    [TokenType.MarkupItalic]: "#ff0000",
    [TokenType.MarkupUnderline]: "#ff0000",
    [TokenType.MarkupStrikethrough]: "#ff0000",
    [TokenType.MarkupLink]: "#ff0000",
    [TokenType.MarkupLinkLabel]: "#ff0000",
    [TokenType.MarkupLinkUrl]: "#ff0000",
    [TokenType.MarkupHeading]: "#ff0000",
    [TokenType.MarkupHeading1]: "#ff0000",
    [TokenType.MarkupHeading2]: "#ff0000",
    [TokenType.MarkupHeading3]: "#ff0000",
    [TokenType.MarkupHeading4]: "#ff0000",
    [TokenType.MarkupHeading5]: "#ff0000",
    [TokenType.MarkupHeading6]: "#ff0000",
    [TokenType.MarkupList]: "#ff0000",
    [TokenType.MarkupListUnchecked]: "#ff0000",
    [TokenType.MarkupListChecked]: "#ff0000",
    [TokenType.MarkupQuote]: "#ff0000",
    [TokenType.MarkupMath]: "#ff0000",
    [TokenType.MarkupRaw]: "#ff0000",
    [TokenType.MarkupRawBlock]: "#ff0000",
    [TokenType.DiffPlus]: "#ff0000",
    [TokenType.DiffMinus]: "#ff0000",
    [TokenType.DiffDelta]: "#ff0000",
    [TokenType.Tag]: "#ff0000",
    [TokenType.TagDelimiter]: "#ff0000",
    [TokenType.TagAttribute]: "#ff0000",
    [TokenType.TagBuiltin]: "#ff0000",
    [TokenType.None]: "#ff0000",
    [TokenType.Conceal]: "#ff0000",
    [TokenType.Spell]: "#acb6bf8c",
    [TokenType.Nospell]: "#ff0000",
  },
};
